### ISSUE TITLE
Issue with joining Google Group

### ISSUE THREAD

**Issue by skingkong** [pilosa/www#291]
We should prob figure out what we want to do with the Google group. In the meantime, we may want to change the name of that button to Google Group instead of Mailing List?

From form fill:
Hi, I visited your community page [1] and clicked on the link to the mailing list / Google group [2] and got a 403 (or a 404 if I wasn't logged into my GSuite account.)

I'm trying out Pilosa now and I'm very excited about it! We too are using Elasticsearch and finding it might not be ideal for our use case.

[1] https://www.pilosa.com/community/
[2] https://groups.google.com/g/pilosa?pli=1

**Comment by codysoyland** [comment]
I did some digging and discovered that somehow the permissions on the Google Group were set up to not allow public listing of the contents. I changed that setting and now it appears to be working. Note that the link in the description of this ticket is not the same as the link on the website.

**Comment by skingkong** [comment]
Awesome, thanks Cody! Confirmed that it's working now. Closing ticket.
